apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  tags:
    - go
    - website
  link:
    - url: https://github.com/shukibakbuki/scates
    title: scates
    icon: github
spec:
  type: website
  lifecycle: production
  owner: team-b
  system: podcast
