apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: searcher
  description: Searcher
  tags:
    - go
  links:
    - url: https://github.com/shukibakbuki/scates
    title: scates?
    icon: github
spec:
  type: service
  lifecycle: production
  owner: user:guest
